services:
  cbr_deploy_custom_sites:
    build:
      context: ../../..
      dockerfile: ./deploy/docker/cbr_deploy_custom_sites__from_pip/Dockerfile
    platform: linux/amd64
    container_name: cbr_deploy_custom_sites__from_pip
    tty: true
