name       : CI Pipeline - DEV
on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  GIT__BRANCH           : 'dev'
  PACKAGE_NAME          : 'cbr_deploy_custom_sites'
  AWS_ACCESS_KEY_ID     : ${{ secrets.AWS_ACCESS_KEY_ID__470426667096     }}
  AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY__470426667096 }}
  AWS_ACCOUNT_ID        : "654654216424"
  AWS_DEFAULT_REGION    : "eu-west-1"

jobs:

  execute-flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Poetry - Install Dependencies
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/poetry__install@dev

      - name: execute flow
        shell: bash
        run: |
          echo "Deploying lambda function"        
          poetry run python ./cbr_deploy_custom_sites/flows/Flow__Update_CBR_Custom_Zip_File.py
        env:
            FLOW__UPDATE_CBR_CUSTOM_ZIP_FILE__S3_BUCKET     : '654654216424--cbr-deploy--eu-west-1'
            FLOW__UPDATE_CBR_CUSTOM_ZIP_FILE__LAMBDA_NAME   : 'dev__cbr_custom_portuguese'
            FLOW__UPDATE_CBR_CUSTOM_ZIP_FILE__S3_KEY        : 'cbr-custom-websites/cbr_website_beta/dev__cbr_custom_portuguese.zip'
            FLOW__UPDATE_CBR_CUSTOM_ZIP_FILE__GH_SOURCE_CODE: 'https://github.com/the-cyber-boardroom/cbr-custom--portuguese/archive/refs/heads/dev.zip'

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Poetry - Install Dependencies
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/poetry__install@dev
        with:
          pip_install: '-r requirements-test.txt'

      - name: Run Unit Tests (using Poetry)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/poetry__run-unit-tests@dev
        with:
          test_target: 'tests'


  increment-tag:
    name: Increment Tag - DEV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag (for DEV)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type : 'minor'
    needs:
      - run-unit-tests

